// AUTO-GENERATED by scripts/generate-certificates.mjs — do not edit by hand.
import type { Certificate } from "./types";

export const CERTIFICATES: Certificate[] = [
  {
    "email": "sajiya@example.com",
    "name": "Sajiya Aryal",
    "event": "Linux 101",
    "eventSlug": "linux-101",
    "issueYear": 2026,
    "date": "2026-07-03",
    "templateId": "demo"
  },
  {
    "email": "aakrisht@example.com",
    "name": "Aakrisht Sharma Paudel",
    "event": "Linux 101",
    "eventSlug": "linux-101",
    "issueYear": 2026,
    "date": "2026-07-03",
    "templateId": "demo"
  },
  {
    "email": "suubha@example.com",
    "name": "Subha Sandesh Sharma Neupane",
    "event": "Linux 101",
    "eventSlug": "linux-101",
    "issueYear": 2026,
    "date": "2026-07-03",
    "templateId": "demo"
  },
  {
    "email": "subha@example.com",
    "name": "Subha Sandesh Sharma Neupane",
    "event": "Linux 101",
    "eventSlug": "linux-101",
    "issueYear": 2026,
    "date": "2026-07-03",
    "templateId": "demo"
  }
];

const normalizeEmail = (email: string): string => email.trim().toLowerCase();
const keyOf = (templateId: string, email: string): string => `${templateId}|${normalizeEmail(email)}`;

const BY_KEY = new Map(CERTIFICATES.map((c) => [keyOf(c.templateId, c.email), c]));

const BY_EMAIL = new Map<string, Certificate[]>();
for (const cert of CERTIFICATES) {
  const email = normalizeEmail(cert.email);
  BY_EMAIL.set(email, [...(BY_EMAIL.get(email) ?? []), cert]);
}

export const getCertificateByTemplateAndEmail = (templateId: string, email: string): Certificate | undefined =>
  BY_KEY.get(keyOf(templateId, email));

export const getCertificatesByEmail = (email: string): Certificate[] =>
  BY_EMAIL.get(normalizeEmail(email)) ?? [];

export const getCertificatePath = (templateId: string, email: string): string =>
  `/cert?templateId=${templateId}&email=${normalizeEmail(email)}`;

export type { Certificate } from "./types";
