// AUTO-GENERATED by scripts/generate-certificates.mjs — do not edit by hand.
import type { Certificate } from "./types";

export const CERTIFICATES: Certificate[] = [
  {
    "email": "test@example.com",
    "name": "Test1",
    "eventSlug": "2026-linux101",
    "templateId": "2026-linux101-participation"
  },
  {
    "email": "test2@example.com",
    "name": "Test2",
    "eventSlug": "2026-linux101",
    "templateId": "2026-linux101-mentor"
  },
  {
    "email": "test3@example.com",
    "name": "Test3",
    "eventSlug": "2026-linux101",
    "templateId": "2026-linux101-achievement"
  }
];

const normalizeEmail = (email: string): string => email.trim().toLowerCase();
const keyOf = (templateId: string, email: string): string => `${templateId}|${normalizeEmail(email)}`;

const BY_KEY = new Map(CERTIFICATES.map((c) => [keyOf(c.templateId, c.email), c]));

const BY_EMAIL = new Map<string, Certificate[]>();
for (const cert of CERTIFICATES) {
  const email = normalizeEmail(cert.email);
  BY_EMAIL.set(email, [...(BY_EMAIL.get(email) ?? []), cert]);
}

export const getCertificateByTemplateAndEmail = (templateId: string, email: string): Certificate | undefined =>
  BY_KEY.get(keyOf(templateId, email));

export const getCertificatesByEmail = (email: string): Certificate[] =>
  BY_EMAIL.get(normalizeEmail(email)) ?? [];

export const getCertificatePath = (templateId: string, email: string): string =>
  `/cert?templateId=${templateId}&email=${normalizeEmail(email)}`;

export type { Certificate } from "./types";
